package com.sarmad.notification.mappers;

import com.sarmad.notification.dtos.AlertRequestDto;
import com.sarmad.notification.entities.AlertEntity;
import com.sarmad.notification.entities.DriverAlertEntity;
import com.sarmad.notification.entities.VehicleAlertEntity;
import com.sarmad.notification.enums.AlertType;
import com.sarmad.notification.enums.SeverityType;
import com.sarmad.notification.enums.StatusType;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface AlertMapper {

    // DTO → AlertEntity
    @Mapping(target = "alertId", ignore = true) // generated by DB
    @Mapping(target = "createdAt", ignore = true) // set in entity constructor
    @Mapping(target = "updatedAt", ignore = true) // set by @PreUpdate
    @Mapping(target = "type", source = "type", qualifiedByName = "mapAlertType")
    @Mapping(target = "severity", source = "severity", qualifiedByName = "mapSeverityType")
    @Mapping(target = "status", source = "status", qualifiedByName = "mapStatusType")
    AlertEntity toAlertEntity(AlertRequestDto dto);


    @Mapping(target = "id", ignore = true)
    @Mapping(target = "alert", ignore = true)
    @Mapping(target = "acknowledgedAt", ignore = true)
    @Mapping(target = "readStatus", constant = "false")
    DriverAlertEntity toDriverAlertEntity(AlertRequestDto dto);


    @Mapping(target = "id", ignore = true)
    @Mapping(target = "alert", ignore = true)
    @Mapping(target = "acknowledgedAt", ignore = true)
    @Mapping(target = "readStatus", constant = "false")
    VehicleAlertEntity toVehicleAlertEntity(AlertRequestDto dto);

    @Mapping(target = "alert", source = "alert")
    void updateDriverAlertWithAlert(@MappingTarget DriverAlertEntity entity, AlertEntity alert);


    @Mapping(target = "alert", source = "alert")
    void updateVehicleAlertWithAlert(@MappingTarget VehicleAlertEntity entity, AlertEntity alert);

    // Enum → String helpers
    @Named("mapAlertType")
    default String mapAlertType(AlertType type) {
        return type != null ? type.name() : null;
    }

    @Named("mapSeverityType")
    default String mapSeverityType(SeverityType severity) {
        return severity != null ? severity.name() : null;
    }

    @Named("mapStatusType")
    default String mapStatusType(StatusType status) {
        return status != null ? status.name() : null;
    }


}


